services:
  - type: web
    name: doc-analyzer
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
